name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 23.20.116.3 >> ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@23.20.116.3 "echo 'SSH connection successful'"

      - name: Pull Latest Code on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@23.20.116.3 "
            cd ci-cd || (mkdir /ci-cd && cd /ci-cd) && 
            git pull origin main
          "

      - name: Install nvm, Latest Node.js, Install Dependencies & Build on EC2
  run: |
    ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@23.20.116.3 "
      # Install nvm if not installed
      if ! command -v nvm &> /dev/null; then
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      fi
      # Source nvm and install latest stable Node.js
      export NVM_DIR=\"\${HOME}/.nvm\"
      [ -s \"\${NVM_DIR}/nvm.sh\" ] && \. \"\${NVM_DIR}/nvm.sh\"
      nvm install stable
      nvm use stable
      node -v
      # Install dependencies and build the project
      cd ci-cd && 
      npm install && 
      npm run build
    "

       

      - name: Restart Next.js with PM2 on EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@23.20.116.3 "
            cd ci-cd && 
            pm2 restart next-app || pm2 start npm --name 'next-app' -- start
          "
