name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa  # Load private RSA key from GitHub secrets
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 23.20.116.3 >> ~/.ssh/known_hosts

           # Add the passphrase if needed
            echo "${{ secrets.SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Print SSH Private Key (For Debugging)
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}"  # Print private key to logs (use for testing only)

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@23.20.116.3 "echo 'SSH connection successful'"

      - name: Deploy Next.js to EC2
        uses: appleboy/scp-action@master
        with:
          host: 23.20.116.3
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}  # Load RSA private key from GitHub secrets
          source: "."  
          target: "/ci-cd"

      - name: Restart Next.js with PM2
        uses: appleboy/ssh-action@master
        with:
          host: 23.20.116.3
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}  # Load RSA private key from GitHub secrets
          script: |
            cd /ci-cd
            npm install
            npm run build
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
