name: Deploy Next.js to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets._SSH_KEYAWS }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 23.20.116.3 >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@23.20.116.3 "echo 'SSH connection successful'"

      - name: Deploy Next.js to EC2
        uses: appleboy/scp-action@master
        with:
          host: 23.20.116.3
          username: ubuntu
          key: ${{ secrets._SSH_KEYAWS }}  # Ensure you're using the correct secret key here
          source: "."  
          target: "/ci-cd"  # Specify the target folder where your app will be deployed

      - name: Restart Next.js with PM2
        uses: appleboy/ssh-action@master
        with:
          host: 23.20.116.3
          username: ubuntu
          key: ${{ secrets._SSH_KEYAWS }}  # Use the same key as the previous step
          script: |
            cd /ci-cd
            npm install
            npm run build
            pm2 restart next-app || pm2 start npm --name "next-app" -- start
